version: "3.9"
services:
  resume:
    image: python:3.11
    working_dir: /app
    command: python -m http.server 80
    volumes:
      - ./build:/app
    healthcheck:
      test: ["CMD", "curl" ,"http://localhost"]
      interval: 6s
      timeout: 3s
      retries: 30

  puppeteer:
    build:
      context: pdf
      dockerfile: Dockerfile
    volumes:
      - ./pdf:/home/pptruser/pdf
    command: node ./pdf/export.js "http://resume/" "pdf/out/resume.pdf"
    cap_add:
      - SYS_ADMIN
    depends_on:
      resume:
        condition: service_healthy
