name: Check

on: pull_request

env:
  TZ: Asia/Tokyo

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}
      - run: npm ci

  lint:
    name: Lint
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    needs:
      - setup
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}
      - run: npm run lint

  build:
    name: Build
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    needs:
      - setup
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}
      - run: npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: ./build/

  test:
    name: Test
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    needs:
      - setup
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}
      - run: npm run test

  e2e:
    name: E2E Test
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    needs:
      - setup
      - generate_pdf
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
      - run: |
          mkdir -p ./pdf/out
          mv -v pdf_out/* ./pdf/out
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}
      - run: npm run test:e2e

  generate_pdf:
    name: Generate PDF
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    needs:
      - build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
      - run: npm run generate:pdf
      - uses: actions/upload-artifact@v4
        with:
          name: pdf_out
          path: ./pdf/out
