name: Check

on: pull_request

jobs:
  check:
    name: Check
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12"
      - run: yarn install --immutable
      - run: yarn lint
      - run: yarn check:link
