name: Check

on: pull_request

env:
  TZ: Asia/Tokyo
  NODE_OPTIONS: --openssl-legacy-provider

jobs:
  check:
    name: Check
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "18"
      - run: yarn install
      - run: yarn lint
      - run: yarn check:link
