name: Refresh components data

on:
  workflow_dispatch:
  schedule:
    - cron: '0 15 * * SUN'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}
      - run: npm ci

  refresh:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    needs:
      - setup
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}
      - run: npm run refresh-components-data
        env:
          GITHUB_PAT: ${{ secrets.X_GITHUB_PAT }}
      - uses: peter-evans/create-pull-request@v5
        id: cpr
        with:
          token: ${{ secrets.X_GITHUB_PAT_AUTOMATED }}
          author: ${{ secrets.X_GITHUB_AUTOMATED_AUTHOR }}
          commit-message: Update components data
          delete-branch: true
          title: Update components data
          labels: |
            automated
