name: Schedule

on: pull_request

jobs:
  schedule:
    name: Check
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: npm install
      - id: check_link
        run: npm run check:link > ./out/check_link_result.txt 2>&1
        continue-on-error: true
      - run: |
          CHECK_LINK_RESULT="$(cat ./out/check_link_result.txt)"
          CHECK_LINK_RESULT="${CHECK_LINK_RESULT//'%'/'%25'}"
          CHECK_LINK_RESULT="${CHECK_LINK_RESULT//$'\n'/'%0A'}"
          CHECK_LINK_RESULT="${CHECK_LINK_RESULT//$'\r'/'%0D'}"
          echo "::set-env name=CHECK_LINK_RESULT::$CHECK_LINK_RESULT"
      - uses: JasonEtco/create-an-issue@v2
        if: steps.check_link.outcome == 'failure'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CHECK_LINK_RESULT: ${{ env.CHECK_LINK_RESULT }}
        with:
          filename: .github/issue_template_link_check.md
