name: Schedule

on: pull_request

jobs:
  schedule:
    name: Check
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: npm install
      - id: check_link
        run: npm run check:link > "./check_link_result.md" 2>&1
      - run: export CHECK_LINK_RESULT="$(cat "./check_link_result.md")"
        if: always()
      - uses: JasonEtco/create-an-issue@v2
        if: steps.check_link.outcome == 'failure'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CHECK_LINK_RESULT: ${{ env.CHECK_LINK_RESULT }}
        with:
          filename: .github/issue_template_link_check.md
