name: Schedule

on: pull_request

jobs:
  schedule:
    name: Check
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: peter-evans/link-checker@v1
        with:
          args: -v -r docs/
      - uses: peter-evans/create-issue-from-file@v2
        with:
          title: Link Checker Report
          content-filepath: ./link-checker/out.md
          labels: report, automated issue
